<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkplaceReservationSystem.Application\WorkplaceReservationSystem.Application-dev.csproj" />
    <ProjectReference Include="..\WorkplaceReservationSystem.Domain\WorkplaceReservationSystem.Domain-dev.csproj" />
  </ItemGroup>

</Project>
